# dependencies
# gems: jekyll-paginate
# Site settings
title: Riccardo Casatta
email: riccardo.casatta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creative Engineer
baseurl: / # the subpath of your site, e.g. /blog
url: http://rcasatta.github.io # the base hostname & protocol for your site
urlnohttp: rcasatta.github.io # the base hostname & protocol for your site
twitter_username: RCasatta
github_username:  RCasatta

# Build settings
#markdown: kramdown
#paginate: 5
permalink: pretty
lightning_node_url: 02c095d069538f96bf14c5f90f6c0851bdf354a0ec86039a24bf38a73f705adc2c@dmenp4vo7u2xlzt7rq3v5foxzxsemegpczx5jx2pknzz5xafabnuezyd.onion:9735

github:
  repo: https://github.com/RCasatta/rcasatta.github.io
  editpost: https://github.com/RCasatta/rcasatta.github.io/edit/master/
